[package]
name = "nyandere"
version = "0.1.0"
edition = "2024"

[dependencies]
bsdiff = "0.2.1"
color-print = "0.3.7"
compact_str = "0.9.0"
flate2 = { version = "1.1.2", features = ["zlib"] }
foldhash = "0.1.5"
lexopt = "0.3.1"
quick-error = "2.0.1"
sha3 = "0.10.8"
